<?php
return array (
  39 => 
  array (
    'id' => '39',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '情话组',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
    'seotitle' => NULL,
    'seokeywords' => NULL,
    'seodescription' => NULL,
    'prefix_url' => NULL,
    'image' => NULL,
  ),
  40 => 
  array (
    'id' => '40',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '情书',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '情书类',
    'seotitle' => NULL,
    'seokeywords' => NULL,
    'seodescription' => NULL,
    'prefix_url' => NULL,
    'image' => NULL,
  ),
  41 => 
  array (
    'id' => '41',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '日常问候',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/rcwh/',
    'image' => NULL,
  ),
  42 => 
  array (
    'id' => '42',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '贺词大全',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/hcdq/',
    'image' => NULL,
  ),
  43 => 
  array (
    'id' => '43',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '其他短信',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/qtdx/',
    'image' => NULL,
  ),
  44 => 
  array (
    'id' => '44',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '中国传统节',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/zgct/',
    'image' => NULL,
  ),
  45 => 
  array (
    'id' => '45',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '西方传统节',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/xfct/',
    'image' => NULL,
  ),
  46 => 
  array (
    'id' => '46',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '二十四节气',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/essj/',
    'image' => NULL,
  ),
  47 => 
  array (
    'id' => '47',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '网络节日',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/wljr/',
    'image' => NULL,
  ),
  48 => 
  array (
    'id' => '48',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '主题日',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/ztr/',
    'image' => NULL,
  ),
  49 => 
  array (
    'id' => '49',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '纪念日',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/jnr/',
    'image' => NULL,
  ),
  50 => 
  array (
    'id' => '50',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '爱情宝典',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/aqbd/',
    'image' => NULL,
  ),
  51 => 
  array (
    'id' => '51',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '关系',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_list_deam',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/wish/gx/',
    'image' => NULL,
  ),
  52 => 
  array (
    'id' => '52',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '日常歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/rcxh/',
    'image' => NULL,
  ),
  53 => 
  array (
    'id' => '53',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '小学生歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/xxsx/',
    'image' => NULL,
  ),
  54 => 
  array (
    'id' => '54',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '十二生肖歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/sesx/',
    'image' => NULL,
  ),
  55 => 
  array (
    'id' => '55',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '四大名著歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/sdmz/',
    'image' => NULL,
  ),
  56 => 
  array (
    'id' => '56',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '历史人物歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/lsrw/',
    'image' => NULL,
  ),
  57 => 
  array (
    'id' => '57',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '四季歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/sjxh/',
    'image' => NULL,
  ),
  58 => 
  array (
    'id' => '58',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '节日歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/jrxh/',
    'image' => NULL,
  ),
  59 => 
  array (
    'id' => '59',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '情绪歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/qxxh/',
    'image' => NULL,
  ),
  60 => 
  array (
    'id' => '60',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '气象歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/qxxh/',
    'image' => NULL,
  ),
  61 => 
  array (
    'id' => '61',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '数字歇后语',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => 'type_xhy',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '/xhy/szxh/',
    'image' => NULL,
  ),
  62 => 
  array (
    'id' => '62',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '人物',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '',
    'image' => NULL,
  ),
  63 => 
  array (
    'id' => '63',
    'siteid' => '1',
    'module' => 'content',
    'modelid' => '0',
    'name' => '常用',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
    'seotitle' => '',
    'seokeywords' => '',
    'seodescription' => '',
    'prefix_url' => '',
    'image' => NULL,
  ),
);
?>